<?php

namespace Database\Seeders;

use App\Models\CatalogoCuenta;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CatalogoCuentaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cuentas = [
            ['codigo' => '1',        'cuenta' => 'ACTIVO',                              'cuenta_padre_id' => null],
            ['codigo' => '11',       'cuenta' => 'ACTIVO CORRIENTE',                    'cuenta_padre_id' => 1],
            ['codigo' => '1101',     'cuenta' => 'EFECTIVO Y EQUIVALENTES DE EFECTIVO', 'cuenta_padre_id' => 2],
            ['codigo' => '110101',   'cuenta' => 'Caja General',                        'cuenta_padre_id' => 3],
            ['codigo' => '110102',   'cuenta' => 'Caja Chica',                          'cuenta_padre_id' => 3],
            ['codigo' => '110103',   'cuenta' => 'Bancos',                              'cuenta_padre_id' => 3],
            ['codigo' => '11010301', 'cuenta' => 'Cuenta Corriente',                    'cuenta_padre_id' => 6],
            ['codigo' => '11010302', 'cuenta' => 'Cuenta de Ahorro',                    'cuenta_padre_id' => 6],
            ['codigo' => '11010303', 'cuenta' => 'Depósitos a Plazo',                   'cuenta_padre_id' => 6],
            ['codigo' => '1102',     'cuenta' => 'INVERSIONES FINANCIERAS A CORTO PLAZO', 'cuenta_padre_id' => 2],
            ['codigo' => '110201',   'cuenta' => 'Depósitos a Plazo de 91 a 365 días',  'cuenta_padre_id' => 10],
            ['codigo' => '110202',   'cuenta' => 'Instrumentos Financieros a Corto Plazo', 'cuenta_padre_id' => 10],
            ['codigo' => '110203',   'cuenta' => 'Otros Títulos Valores',               'cuenta_padre_id' => 10],
            ['codigo' => '1103',     'cuenta' => 'CUENTAS POR COBRAR',                  'cuenta_padre_id' => 2],
            ['codigo' => '1104',     'cuenta' => '(R) ESTIMACION PARA CUENTAS INCOBRABLES', 'cuenta_padre_id' => 2],
            ['codigo' => '1105',     'cuenta' => 'DOCUMENTOS POR COBRAR',               'cuenta_padre_id' => 2],
            ['codigo' => '1106',     'cuenta' => 'LLAMAMIENTOS DE CAPITAL',             'cuenta_padre_id' => 2],
            ['codigo' => '1107',     'cuenta' => 'PRESTAMOS A EMPLEADOS Y ACCIONISTAS', 'cuenta_padre_id' => 2],
            ['codigo' => '1108',     'cuenta' => 'OTRAS CUENTAS POR COBRAR',            'cuenta_padre_id' => 2],
            ['codigo' => '110801',   'cuenta' => 'Anticipos a Cuentas por Pagar Comerciales', 'cuenta_padre_id' => 19],
            ['codigo' => '110802',   'cuenta' => 'Anticipos a Empleados',               'cuenta_padre_id' => 19],
            ['codigo' => '110803',   'cuenta' => 'Deudores Varios',                     'cuenta_padre_id' => 19],
            ['codigo' => '1109',     'cuenta' => 'INVENTARIOS',                         'cuenta_padre_id' => 2],
            ['codigo' => '1110',     'cuenta' => '(R) ESTIMACION POR DETERIORO DE LOS INVENTARIOS', 'cuenta_padre_id' => 2],
            ['codigo' => '1111',     'cuenta' => 'GASTOS PAGADOS POR ANTICIPADOS',      'cuenta_padre_id' => 2],
            ['codigo' => '111101',   'cuenta' => 'Seguros',                             'cuenta_padre_id' => 25],
            ['codigo' => '111102',   'cuenta' => 'Alquileres',                          'cuenta_padre_id' => 25],
            ['codigo' => '111103',   'cuenta' => 'Papelería y Útiles',                  'cuenta_padre_id' => 25],
            ['codigo' => '111104',   'cuenta' => 'Pago a Cuenta',                       'cuenta_padre_id' => 25],
            ['codigo' => '111105',   'cuenta' => 'Otros Gastos Pagados por Anticipados', 'cuenta_padre_id' => 25],
            ['codigo' => '1112',     'cuenta' => 'CREDITO FISCAL',                      'cuenta_padre_id' => 2],
            ['codigo' => '1113',     'cuenta' => 'IVA PAGADO POR ANTICIPADO',           'cuenta_padre_id' => 2],
            ['codigo' => '111301',   'cuenta' => 'IVA Percibido',                       'cuenta_padre_id' => 32],
            ['codigo' => '111302',   'cuenta' => 'IVA Retenido',                        'cuenta_padre_id' => 32],
            ['codigo' => '12',       'cuenta' => 'ACTIVOS NO CORRIENTES',               'cuenta_padre_id' => 1],
            ['codigo' => '1201',     'cuenta' => 'PROPIEDAD PLANTA Y EQUIPO',           'cuenta_padre_id' => 35],
            ['codigo' => '120101',   'cuenta' => 'Terreno',                             'cuenta_padre_id' => 36],
            ['codigo' => '120102',   'cuenta' => 'Edificio',                            'cuenta_padre_id' => 36],
            ['codigo' => '120103',   'cuenta' => 'Instalaciones',                       'cuenta_padre_id' => 36],
            ['codigo' => '120104',   'cuenta' => 'Equipo de Reparto',                   'cuenta_padre_id' => 36],
            ['codigo' => '120105',   'cuenta' => 'Mobiliario y Equipo',                 'cuenta_padre_id' => 36],
            ['codigo' => '1202',     'cuenta' => '(R) DEPRECIACIONES',                  'cuenta_padre_id' => 35],
            ['codigo' => '120201',   'cuenta' => 'Edificios',                           'cuenta_padre_id' => 42],
            ['codigo' => '120202',   'cuenta' => 'Instalaciones',                       'cuenta_padre_id' => 42],
            ['codigo' => '120203',   'cuenta' => 'Equipo de Reparto',                   'cuenta_padre_id' => 42],
            ['codigo' => '120204',   'cuenta' => 'Mobiliario y Equipo',                 'cuenta_padre_id' => 42],
            ['codigo' => '1203',     'cuenta' => '(R) DETERIORO DE VALOR DE PROPIEDAD DE PLANTA Y EQUIPO', 'cuenta_padre_id' => 35],
            ['codigo' => '120301',   'cuenta' => 'Terreno',                             'cuenta_padre_id' => 47],
            ['codigo' => '120302',   'cuenta' => 'Edificio',                            'cuenta_padre_id' => 47],
            ['codigo' => '120303',   'cuenta' => 'Instalaciones',                       'cuenta_padre_id' => 47],
            ['codigo' => '120304',   'cuenta' => 'Equipo de Reparto',                   'cuenta_padre_id' => 47],
            ['codigo' => '120305',   'cuenta' => 'Mobiliario y Equipo',                 'cuenta_padre_id' => 47],
            ['codigo' => '1204',     'cuenta' => 'INTANGIBLES',                         'cuenta_padre_id' => 35],
            ['codigo' => '120401',   'cuenta' => 'Crédito Mercantil',                   'cuenta_padre_id' => 53],
            ['codigo' => '120402',   'cuenta' => 'Patentes y Marcas',                   'cuenta_padre_id' => 53],
            ['codigo' => '120403',   'cuenta' => 'Licencias',                           'cuenta_padre_id' => 53],
            ['codigo' => '1205',     'cuenta' => '(R) AMORTIZACION DE INTANGIBLES',     'cuenta_padre_id' => 35],
            ['codigo' => '120501',   'cuenta' => 'Crédito Mercantil',                   'cuenta_padre_id' => 57],
            ['codigo' => '120502',   'cuenta' => 'Patentes y Marcas',                   'cuenta_padre_id' => 57],
            ['codigo' => '120503',   'cuenta' => 'Licencias',                           'cuenta_padre_id' => 57],
            ['codigo' => '1206',     'cuenta' => '(R) DETERIORO DE VALOR INTANGIBLE',   'cuenta_padre_id' => 35],
            ['codigo' => '120601',   'cuenta' => 'Crédito Mercantil',                   'cuenta_padre_id' => 61],
            ['codigo' => '120602',   'cuenta' => 'Patentes y Marcas',                   'cuenta_padre_id' => 61],
            ['codigo' => '120603',   'cuenta' => 'Licencias',                           'cuenta_padre_id' => 61],
            ['codigo' => '1207',     'cuenta' => 'INVERSIONES EN ASOCIADOS',            'cuenta_padre_id' => 35],
            ['codigo' => '1208',     'cuenta' => 'ACTIVO POR IMPUESTO SOBRE LA RENTA DIFERIDO', 'cuenta_padre_id' => 35],
            ['codigo' => '2',        'cuenta' => 'PASIVO',                              'cuenta_padre_id' => null],
            ['codigo' => '21',       'cuenta' => 'PASIVO CORRIENTE',                    'cuenta_padre_id' => 67],
            ['codigo' => '2101',     'cuenta' => 'SOBREGIROS BANCARIOS',                'cuenta_padre_id' => 68],
            ['codigo' => '2102',     'cuenta' => 'CUENTAS POR PAGAR COMERCIALES',       'cuenta_padre_id' => 68],
            ['codigo' => '210201',   'cuenta' => 'Locales',                             'cuenta_padre_id' => 70],
            ['codigo' => '210202',   'cuenta' => 'Del Exterior',                        'cuenta_padre_id' => 70],
            ['codigo' => '2103',     'cuenta' => 'DOCUMENTOS POR PAGAR DESCONTADOS',    'cuenta_padre_id' => 68],
            ['codigo' => '210301',   'cuenta' => 'Pagares',                             'cuenta_padre_id' => 73],
            ['codigo' => '210302',   'cuenta' => 'Letras de Cambio',                    'cuenta_padre_id' => 73],
            ['codigo' => '210303',   'cuenta' => 'Bonos',                               'cuenta_padre_id' => 73],
            ['codigo' => '2104',     'cuenta' => 'OTROS TITULOS Y VALORES',             'cuenta_padre_id' => 68],
            ['codigo' => '210401',   'cuenta' => 'Pagares',                             'cuenta_padre_id' => 77],
            ['codigo' => '210402',   'cuenta' => 'Letras de Cambio',                    'cuenta_padre_id' => 77],
            ['codigo' => '210403',   'cuenta' => 'Bonos',                               'cuenta_padre_id' => 77],
            ['codigo' => '210404',   'cuenta' => 'Otros Títulos y Valores',             'cuenta_padre_id' => 77],
            ['codigo' => '2105',     'cuenta' => 'PRESTAMOS POR PAGAR',                 'cuenta_padre_id' => 68],
            ['codigo' => '210501',   'cuenta' => 'Bancarios',                           'cuenta_padre_id' => 82],
            ['codigo' => '210502',   'cuenta' => 'Accionistas',                         'cuenta_padre_id' => 82],
            ['codigo' => '210503',   'cuenta' => 'Otros',                               'cuenta_padre_id' => 82],
            ['codigo' => '2106',     'cuenta' => 'RETENCIONES POR PAGAR',               'cuenta_padre_id' => 68],
            ['codigo' => '210601',   'cuenta' => 'ISSS (Salud)',                        'cuenta_padre_id' => 86],
            ['codigo' => '210602',   'cuenta' => 'ISSS (Pensión)',                      'cuenta_padre_id' => 86],
            ['codigo' => '210603',   'cuenta' => 'AFP',                                 'cuenta_padre_id' => 86],
            ['codigo' => '210604',   'cuenta' => 'Renta',                               'cuenta_padre_id' => 86],
            ['codigo' => '210605',   'cuenta' => 'IVA',                                 'cuenta_padre_id' => 86],
            ['codigo' => '210606',   'cuenta' => 'Otras Retenciones',                   'cuenta_padre_id' => 86],
            ['codigo' => '2107',     'cuenta' => 'OBLIGACIONES POR BENEFICIOS DE EMPLEADOS A CORTO PLAZO', 'cuenta_padre_id' => 68],
            ['codigo' => '210701',   'cuenta' => 'ISSS (Salud)',                        'cuenta_padre_id' => 93],
            ['codigo' => '210702',   'cuenta' => 'ISSS (Pension)',                      'cuenta_padre_id' => 93],
            ['codigo' => '210703',   'cuenta' => 'AFP',                                 'cuenta_padre_id' => 93],
            ['codigo' => '210704',   'cuenta' => 'INSAFORP',                            'cuenta_padre_id' => 93],
            ['codigo' => '210705',   'cuenta' => 'Vacaciones',                          'cuenta_padre_id' => 93],
            ['codigo' => '210706',   'cuenta' => 'Aguinaldo',                           'cuenta_padre_id' => 93],
            ['codigo' => '210707',   'cuenta' => 'Indemnizaciones Convenidas',          'cuenta_padre_id' => 93],
            ['codigo' => '2108',     'cuenta' => 'DIVIDENDOS POR PAGAR',                'cuenta_padre_id' => 68],
            ['codigo' => '2109',     'cuenta' => 'IVA DEBITO FISCAL',                   'cuenta_padre_id' => 68],
            ['codigo' => '2110',     'cuenta' => 'IVA PERCIBIDO Y RETENIDO POR PAGAR',  'cuenta_padre_id' => 68],
            ['codigo' => '211001',   'cuenta' => 'IVA Percibido',                       'cuenta_padre_id' => 103],
            ['codigo' => '211002',   'cuenta' => 'IVA Retenido',                        'cuenta_padre_id' => 103],
            ['codigo' => '2111',     'cuenta' => 'IMPUESTOS POR PAGAR',                 'cuenta_padre_id' => 68],
            ['codigo' => '211101',   'cuenta' => 'Pago a Cuenta',                       'cuenta_padre_id' => 106],
            ['codigo' => '211102',   'cuenta' => 'Renta',                               'cuenta_padre_id' => 106],
            ['codigo' => '211103',   'cuenta' => 'IVA',                                 'cuenta_padre_id' => 106],
            ['codigo' => '211104',   'cuenta' => 'Otros',                               'cuenta_padre_id' => 106],
            ['codigo' => '2112',     'cuenta' => 'CUENTAS POR PAGAR',                   'cuenta_padre_id' => 68],
            ['codigo' => '2113',     'cuenta' => 'INTERESES POR PAGAR',                 'cuenta_padre_id' => 68],
            ['codigo' => '22',       'cuenta' => 'PASIVO NO CORRIENTE',                 'cuenta_padre_id' => 67],
            ['codigo' => '2201',     'cuenta' => 'PRESTAMOS POR PAGAR',                 'cuenta_padre_id' => 113],
            ['codigo' => '2202',     'cuenta' => 'DOCUMENTOS POR PAGAR',                'cuenta_padre_id' => 113],
            ['codigo' => '2203',     'cuenta' => 'INGRESOS DIFERIDOS',                  'cuenta_padre_id' => 113],
            ['codigo' => '2204',     'cuenta' => 'PROVISION PARA OBLIGACIONES LABORALES', 'cuenta_padre_id' => 113],
            ['codigo' => '2205',     'cuenta' => 'PASIVO POR IMPUESTO SOBRE LA RENTA DIFERIDO', 'cuenta_padre_id' => 113],
            ['codigo' => '3',        'cuenta' => 'PATRIMONIO',                          'cuenta_padre_id' => null],
            ['codigo' => '31',       'cuenta' => 'CAPITAL CONTABLE',                    'cuenta_padre_id' => 119],
            ['codigo' => '3101',     'cuenta' => 'CAPITAL SOCIAL',                      'cuenta_padre_id' => 120],
            ['codigo' => '3102',     'cuenta' => '(R) CAPITAL SUSCRITO NO PAGADO',      'cuenta_padre_id' => 120],
            ['codigo' => '3103',     'cuenta' => 'RESERVA LEGAL',                       'cuenta_padre_id' => 120],
            ['codigo' => '3104',     'cuenta' => 'RESERVAS VOLUNTARIAS',                'cuenta_padre_id' => 120],
            ['codigo' => '3105',     'cuenta' => 'UTILIDADES RETENIDAS',                'cuenta_padre_id' => 120],
            ['codigo' => '3106',     'cuenta' => 'UTILIDAD DEL EJERCICIO',              'cuenta_padre_id' => 120],
            ['codigo' => '3107',     'cuenta' => '(R) DEFICIT',                         'cuenta_padre_id' => 120],
            ['codigo' => '310701',   'cuenta' => 'Déficit Acumulado',                   'cuenta_padre_id' => 127],
            ['codigo' => '310702',   'cuenta' => 'Déficit del Presente Ejercicio',      'cuenta_padre_id' => 127],
            ['codigo' => '4',        'cuenta' => 'CUENTAS DE RESULTADOS DEUDORAS',      'cuenta_padre_id' => null],
            ['codigo' => '41',       'cuenta' => 'COSTOS',                              'cuenta_padre_id' => 130],
            ['codigo' => '4101',     'cuenta' => 'COMPRAS',                             'cuenta_padre_id' => 131],
            ['codigo' => '4102',     'cuenta' => 'GASTOS SOBRE COMPRAS',                'cuenta_padre_id' => 131],
            ['codigo' => '4103',     'cuenta' => '(R) DEVOLUCIONES Y REBAJAS SOBRE VENTAS', 'cuenta_padre_id' => 131],
            ['codigo' => '42',       'cuenta' => 'GASTOS',                              'cuenta_padre_id' => 130],
            ['codigo' => '4201',     'cuenta' => 'GASTOS DE ADMINISTRACION',            'cuenta_padre_id' => 135],
            ['codigo' => '420101',   'cuenta' => 'Sueldos',                             'cuenta_padre_id' => 136],
            ['codigo' => '420102',   'cuenta' => 'Comisiones',                          'cuenta_padre_id' => 136],
            ['codigo' => '420103',   'cuenta' => 'Vacaciones',                          'cuenta_padre_id' => 136],
            ['codigo' => '420104',   'cuenta' => 'Bonificaciones',                      'cuenta_padre_id' => 136],
            ['codigo' => '420105',   'cuenta' => 'Aguinaldos',                          'cuenta_padre_id' => 136],
            ['codigo' => '420106',   'cuenta' => 'Horas Extras',                        'cuenta_padre_id' => 136],
            ['codigo' => '420107',   'cuenta' => 'Viáticos',                            'cuenta_padre_id' => 136],
            ['codigo' => '420108',   'cuenta' => 'Indemnizaciones',                     'cuenta_padre_id' => 136],
            ['codigo' => '420109',   'cuenta' => 'Atención al Personal',                'cuenta_padre_id' => 136],
            ['codigo' => '420110',   'cuenta' => 'ISSS (Salud)',                        'cuenta_padre_id' => 136],
            ['codigo' => '420111',   'cuenta' => 'ISSS (Pensión)',                      'cuenta_padre_id' => 136],
            ['codigo' => '420112',   'cuenta' => 'AFP',                                 'cuenta_padre_id' => 136],
            ['codigo' => '420113',   'cuenta' => 'INSAFORP',                            'cuenta_padre_id' => 136],
            ['codigo' => '420114',   'cuenta' => 'Honorarios',                          'cuenta_padre_id' => 136],
            ['codigo' => '420115',   'cuenta' => 'Seguros',                             'cuenta_padre_id' => 136],
            ['codigo' => '420116',   'cuenta' => 'Transporte',                          'cuenta_padre_id' => 136],
            ['codigo' => '420117',   'cuenta' => 'Agua',                                'cuenta_padre_id' => 136],
            ['codigo' => '420118',   'cuenta' => 'Comunicaciones',                      'cuenta_padre_id' => 136],
            ['codigo' => '420119',   'cuenta' => 'Energía Eléctrica',                   'cuenta_padre_id' => 136],
            ['codigo' => '420120',   'cuenta' => 'Deterioro del valor de las Cuentas por Cobrar', 'cuenta_padre_id' => 136],
            ['codigo' => '420121',   'cuenta' => 'Papelería y Útiles',                  'cuenta_padre_id' => 136],
            ['codigo' => '420122',   'cuenta' => 'Depreciación',                        'cuenta_padre_id' => 136],
            ['codigo' => '420123',   'cuenta' => 'Mantenimiento y Reparación del Mobiliario', 'cuenta_padre_id' => 136],
            ['codigo' => '420124',   'cuenta' => 'Mantenimiento y Reparación de Edificios',   'cuenta_padre_id' => 136],
            ['codigo' => '420125',   'cuenta' => 'Mantenimiento y Reparación de Equipo',      'cuenta_padre_id' => 136],
            ['codigo' => '420126',   'cuenta' => 'Publicidad',                          'cuenta_padre_id' => 136],
            ['codigo' => '420127',   'cuenta' => 'Empaques',                            'cuenta_padre_id' => 136],
            ['codigo' => '420128',   'cuenta' => 'Atención A Clientes',                 'cuenta_padre_id' => 136],
            ['codigo' => '420129',   'cuenta' => 'Multas',                              'cuenta_padre_id' => 136],
            ['codigo' => '420130',   'cuenta' => 'Combustibles y Lubricantes',          'cuenta_padre_id' => 136],
            ['codigo' => '420131',   'cuenta' => 'Impuestos Municipales',               'cuenta_padre_id' => 136],
            ['codigo' => '420132',   'cuenta' => 'Inscripciones',                       'cuenta_padre_id' => 136],
            ['codigo' => '420133',   'cuenta' => 'Limpieza',                            'cuenta_padre_id' => 136],
            ['codigo' => '420134',   'cuenta' => 'Alquileres',                          'cuenta_padre_id' => 136],
            ['codigo' => '420135',   'cuenta' => 'Matriculas de Comercio',              'cuenta_padre_id' => 136],
            ['codigo' => '420136',   'cuenta' => 'Donaciones y Contribuciones',         'cuenta_padre_id' => 136],
            ['codigo' => '420137',   'cuenta' => 'Vigilancia',                          'cuenta_padre_id' => 136],
            ['codigo' => '420138',   'cuenta' => 'Uniformes',                           'cuenta_padre_id' => 136],
            ['codigo' => '420139',   'cuenta' => 'Ornato',                              'cuenta_padre_id' => 136],
            ['codigo' => '420140',   'cuenta' => 'Fovial',                              'cuenta_padre_id' => 136],
            ['codigo' => '420141',   'cuenta' => 'Cotrans',                             'cuenta_padre_id' => 136],
            ['codigo' => '420143',   'cuenta' => 'Otros',                               'cuenta_padre_id' => 136],
            ['codigo' => '4202',     'cuenta' => 'GASTOS DE VENTAS',                    'cuenta_padre_id' => 135],
            ['codigo' => '420201',   'cuenta' => 'Sueldos',                             'cuenta_padre_id' => 179],
            ['codigo' => '420202',   'cuenta' => 'Comisiones',                          'cuenta_padre_id' => 179],
            ['codigo' => '420203',   'cuenta' => 'Vacaciones',                          'cuenta_padre_id' => 179],
            ['codigo' => '420204',   'cuenta' => 'Bonificaciones',                      'cuenta_padre_id' => 179],
            ['codigo' => '420205',   'cuenta' => 'Aguinaldos',                          'cuenta_padre_id' => 179],
            ['codigo' => '420206',   'cuenta' => 'Horas Extras',                        'cuenta_padre_id' => 179],
            ['codigo' => '420207',   'cuenta' => 'Viáticos',                            'cuenta_padre_id' => 179],
            ['codigo' => '420208',   'cuenta' => 'Indemnizaciones',                     'cuenta_padre_id' => 179],
            ['codigo' => '420209',   'cuenta' => 'Atención al Personal',                'cuenta_padre_id' => 179],
            ['codigo' => '420210',   'cuenta' => 'ISSS (Salud)',                        'cuenta_padre_id' => 179],
            ['codigo' => '420211',   'cuenta' => 'ISSS (Pensión)',                      'cuenta_padre_id' => 179],
            ['codigo' => '420212',   'cuenta' => 'AFP',                                 'cuenta_padre_id' => 179],
            ['codigo' => '420213',   'cuenta' => 'INSAFORP',                            'cuenta_padre_id' => 179],
            ['codigo' => '420214',   'cuenta' => 'Honorarios',                          'cuenta_padre_id' => 179],
            ['codigo' => '420215',   'cuenta' => 'Seguros',                             'cuenta_padre_id' => 179],
            ['codigo' => '420216',   'cuenta' => 'Transporte',                          'cuenta_padre_id' => 179],
            ['codigo' => '420217',   'cuenta' => 'Agua',                                'cuenta_padre_id' => 179],
            ['codigo' => '420218',   'cuenta' => 'Comunicaciones',                      'cuenta_padre_id' => 179],
            ['codigo' => '420219',   'cuenta' => 'Energía Eléctrica',                   'cuenta_padre_id' => 179],
            ['codigo' => '420220',   'cuenta' => 'Deterioro del valor de las Cuentas por Cobrar', 'cuenta_padre_id' => 179],
            ['codigo' => '420221',   'cuenta' => 'Papelería y Útiles',                  'cuenta_padre_id' => 179],
            ['codigo' => '420222',   'cuenta' => 'Depreciación',                        'cuenta_padre_id' => 179],
            ['codigo' => '420223',   'cuenta' => 'Mantenimiento y Reparación del Mobiliario', 'cuenta_padre_id' => 179],
            ['codigo' => '420224',   'cuenta' => 'Mantenimiento y Reparación de Edificios',   'cuenta_padre_id' => 179],
            ['codigo' => '420225',   'cuenta' => 'Mantenimiento y Reparación de Equipo',      'cuenta_padre_id' => 179],
            ['codigo' => '420226',   'cuenta' => 'Publicidad',                          'cuenta_padre_id' => 179],
            ['codigo' => '420227',   'cuenta' => 'Empaques',                            'cuenta_padre_id' => 179],
            ['codigo' => '420228',   'cuenta' => 'Atención A Clientes',                 'cuenta_padre_id' => 179],
            ['codigo' => '420229',   'cuenta' => 'Multas',                              'cuenta_padre_id' => 179],
            ['codigo' => '420230',   'cuenta' => 'Combustibles y Lubricantes',          'cuenta_padre_id' => 179],
            ['codigo' => '420231',   'cuenta' => 'Impuestos Municipales',               'cuenta_padre_id' => 179],
            ['codigo' => '420232',   'cuenta' => 'Inscripciones',                       'cuenta_padre_id' => 179],
            ['codigo' => '420233',   'cuenta' => 'Limpieza',                            'cuenta_padre_id' => 179],
            ['codigo' => '420234',   'cuenta' => 'Alquileres',                          'cuenta_padre_id' => 179],
            ['codigo' => '420235',   'cuenta' => 'Matriculas de Comercio',              'cuenta_padre_id' => 179],
            ['codigo' => '420236',   'cuenta' => 'Donaciones y Contribuciones',         'cuenta_padre_id' => 179],
            ['codigo' => '420237',   'cuenta' => 'Vigilancia',                          'cuenta_padre_id' => 179],
            ['codigo' => '420238',   'cuenta' => 'Uniformes',                           'cuenta_padre_id' => 179],
            ['codigo' => '420239',   'cuenta' => 'Ornato',                              'cuenta_padre_id' => 179],
            ['codigo' => '420240',   'cuenta' => 'Fovial',                              'cuenta_padre_id' => 179],
            ['codigo' => '420241',   'cuenta' => 'Cotrans',                             'cuenta_padre_id' => 179],
            ['codigo' => '420243',   'cuenta' => 'Otros',                               'cuenta_padre_id' => 179],
            ['codigo' => '4203',     'cuenta' => 'COSTOS FINANCIEROS',                  'cuenta_padre_id' => 135],
            ['codigo' => '420301',   'cuenta' => 'Intereses',                           'cuenta_padre_id' => 222],
            ['codigo' => '420302',   'cuenta' => 'Comisiones Bancarias',                'cuenta_padre_id' => 222],
            ['codigo' => '420303',   'cuenta' => 'Otros',                               'cuenta_padre_id' => 222],
            ['codigo' => '4204',     'cuenta' => 'GASTOS POR IMPUESTO SOBRE LA RENTA CORRIENTE', 'cuenta_padre_id' => 135],
            ['codigo' => '4205',     'cuenta' => 'GASTOS POR IMPUESTO SOBRE LA RENTA DIFERIDO',  'cuenta_padre_id' => 135],
            ['codigo' => '43',       'cuenta' => 'PERDIDAS',                            'cuenta_padre_id' => 130],
            ['codigo' => '4301',     'cuenta' => 'PERDIDAS EN VENTA DE ACTIVO DE EXPLOTACION', 'cuenta_padre_id' => 228],
            ['codigo' => '4302',     'cuenta' => 'PERDIDA POR DETERIORO DE ACTIVOS',    'cuenta_padre_id' => 228],
            ['codigo' => '430201',   'cuenta' => 'Perdida por Deterioro de Inventarios', 'cuenta_padre_id' => 230],
            ['codigo' => '430202',   'cuenta' => 'Perdida por Deterioro de Intangibles', 'cuenta_padre_id' => 230],
            ['codigo' => '430203',   'cuenta' => 'Perdida por Deterioro de Planta y Equipo', 'cuenta_padre_id' => 230],
            ['codigo' => '4303',     'cuenta' => 'PERDIDA POR CASOS FORTUITOS EN ACTIVOS', 'cuenta_padre_id' => 228],
            ['codigo' => '4304',     'cuenta' => 'DETERIORO Y PERDIDAS DE INSTRUMENTOS FINANCIEROS', 'cuenta_padre_id' => 228],
            ['codigo' => '5',        'cuenta' => 'CUENTAS DE RESULTADOS ACREEDORAS',    'cuenta_padre_id' => null],
            ['codigo' => '51',       'cuenta' => 'INGRESOS DE OPERACION',               'cuenta_padre_id' => 236],
            ['codigo' => '5101',     'cuenta' => 'VENTAS',                              'cuenta_padre_id' => 237],
            ['codigo' => '5102',     'cuenta' => '(R) DEVOLUCIONES Y REBAJAS SOBRE COMPRAS', 'cuenta_padre_id' => 237],
            ['codigo' => '5103',     'cuenta' => 'INGRESO POR IMPUESTOS SOBRE LA RENTA DIFERIDOS', 'cuenta_padre_id' => 237],
            ['codigo' => '5104',     'cuenta' => 'REVERSION DE PERDIDAS POR DETERIORO DE ACTIVOS', 'cuenta_padre_id' => 237],
            ['codigo' => '52',       'cuenta' => 'GANANCIAS',                           'cuenta_padre_id' => 236],
            ['codigo' => '5201',     'cuenta' => 'GANANCIAS POR INTERESES',             'cuenta_padre_id' => 242],
            ['codigo' => '5202',     'cuenta' => 'GANANCIAS EN VENTAS DE ACTIVO DE EXPLOTACION', 'cuenta_padre_id' => 242],
            ['codigo' => '5203',     'cuenta' => 'OTRAS GANANCIAS',                     'cuenta_padre_id' => 242],
            ['codigo' => '5204',     'cuenta' => 'REVERSION DE DETERIORO Y GANANCIAS EN VENTA DE INSTRUMENTOS FINANCIEROS', 'cuenta_padre_id' => 242],
            ['codigo' => '6',        'cuenta' => 'CUENTA DE CIERRE',                    'cuenta_padre_id' => null], // ID 247
            ['codigo' => '61',       'cuenta' => 'CUENTA LIQUIDADORA',                  'cuenta_padre_id' => 247],  // ID 248
            ['codigo' => '6101',     'cuenta' => 'PÉRDIDAS Y GANANCIA',                 'cuenta_padre_id' => 248],
        ];

        foreach ($cuentas as &$cuenta) {
            $cuenta['esta_activo'] = 1;
            $cuenta['created_at'] = now();
            $cuenta['updated_at'] = now();
        }

        CatalogoCuenta::query()->insert($cuentas);
    }
}
